<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DreamersCode.PublicProjectTemplate</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    
    <!-- Custom Properties -->
    <DefaultLanguage>en-GB</DefaultLanguage>
    <Authors>Terrence Cassar</Authors>
    <Copyright>$([System.DateTime]::Now.Year) Dreamers Code ©</Copyright>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>$(MSBuildProjectName).xml</DocumentationFile>
    <RepositoryType>git</RepositoryType>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <Description>this is a dummy description</Description>
    <PackageIcon>icon_small.png</PackageIcon>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <!-- Versioning with MinVer -->

    <MinVerDefaultPreReleaseIdentifiers>beta.0</MinVerDefaultPreReleaseIdentifiers>
    
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="icon_small.png" Pack="true" Visible="true" PackagePath="" />
    <None Include="..\..\readme.md" Pack="true" PackagePath="\"/>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="MinVer" Version="7.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
