<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0;</TargetFrameworks>
    <RootNamespace>DreamersCode.Utilities.Lookups.Languages.Tests</RootNamespace>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableMSTestRunner>false</EnableMSTestRunner>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.3.2" />    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DreamersCode.Utilities.Lookups.Languages\DreamersCode.Utilities.Lookups.Languages.csproj" />
  </ItemGroup>

</Project>
